---
- name: Create Jellyfin volume
  community.docker.docker_volume:
    state: present
    name: jellyfin_config

- name: Run Jellyfin container
  community.docker.docker_container:
    name: jellyfin
    image: lscr.io/linuxserver/jellyfin:latest
    state: started
    restart_policy: always
    network_mode: overlay_network
    volumes:
      - jellyfin_config:/config
      - "{{ starr.path }}:/data"
    env:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris