---
- name: Create Radarr volume
  community.docker.docker_volume:
    state: present
    name: radarr_config

- name: Run Radarr container
  community.docker.docker_container:
    name: radarr
    image: lscr.io/linuxserver/radarr:latest
    state: started
    restart_policy: always
    network_mode: overlay_network
    volumes:
      - radarr_config:/config
      - "{{ starr.path }}:/data"
    env:
      PUID: 1000
      PGID: 1000
      TZ: Europe/Paris